# Generated by Django 4.2.16 on 2024-09-14 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_status_task_tasktype_taskhistory_task_type_subtasks_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subtasks',
        ),
    ]
