# Generated by Django 4.2.16 on 2024-09-14 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_delete_subtasks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subtasks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_subtask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtask', to='tasks.task')),
                ('id_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task', to='tasks.task')),
            ],
        ),
    ]
