# Generated by Django 4.2.16 on 2024-09-14 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_subtasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtasks',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
